"""updated schemas and models

Revision ID: 3d8afa3d3d80
Revises: b4a5c6d7e8f9
Create Date: 2026-06-27 12:15:48.126530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3d8afa3d3d80'
down_revision = 'b4a5c6d7e8f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_meetings_is_active'), 'meetings', ['is_active'], unique=False)
    op.create_index(op.f('ix_participants_room_id'), 'participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_rooms_host_id'), 'rooms', ['host_id'], unique=False)
    op.create_index(op.f('ix_rooms_is_active'), 'rooms', ['is_active'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_rooms_is_active'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_host_id'), table_name='rooms')
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_room_id'), table_name='participants')
    op.drop_index(op.f('ix_meetings_is_active'), table_name='meetings')
    # ### end Alembic commands ###